/**
 * Webpack configuration file.
 *
 */

// WordPress webpack config.
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Plugins.
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');
const CopyPlugin = require('copy-webpack-plugin');
const RtlCssPlugin = require('rtlcss-webpack-plugin');

// Utilities.
const path = require('path');

// Directory paths
const SRC_DIR = path.resolve(__dirname, 'assets/src');
const BUILD_DIR = path.resolve(__dirname, 'assets/build');


/**
 * Exports the custom webpack config.
 *
 */
module.exports = {
    // Includes the default webpack config from WordPress.
    ...defaultConfig,
    ...{
        plugins: [
            // Very important! Include WP's plugin config or the
            // world will cease to exist as we know it. This also
            // removes the RTL handling for the moment, but it
            // should be re-added at a later date.
            ...defaultConfig.plugins.filter(
                (filter) => !(filter instanceof RtlCssPlugin)
            ),

            // Removes the empty `.js` files generated by webpack.
            // For this to work correctly, it needs to run after
            // WP has generated its the `*.asset.php` files. This is
            // what `STAGE_AFTER_PROCESS_PLUGINS` allows.
            new RemoveEmptyScriptsPlugin({
                stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
            }),
            // Copies any assets that don't need to be processed to
            // the output folder.
            new CopyPlugin({
                patterns: [
                    {
                        from: SRC_DIR + '/images',
                        to: BUILD_DIR + '/images',
                        noErrorOnMissing: true,
                    },
                    {
                        from: SRC_DIR + '/library',
                        to: BUILD_DIR + '/library',
                        noErrorOnMissing: true,
                    },
                ]
            })
        ]
    },
    performance: {
        maxAssetSize: 512000
    }
};